parameters:
    lrotherfield.notification.class: LRotherfieldBundleNotificationBundleControllerNotificationController

services:
    lrotherfield.notify:
        class: "%lrotherfield.notification.class%"
        arguments:
            session: @session