ri_default:
    resource: "@RIWebServicesBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    
ri_set:
    resource: "@RIWebServicesBundle/Controller/SET/SETController.php"
    type:     annotation
    prefix:   /set

ri_ws:
    resource: "@RIWebServicesBundle/Controller/WS/WSController.php"
    type:     annotation
    prefix:   /ws
    
ri_configuracion_edilicia:
    resource: "@RIWebServicesBundle/Controller/ConfiguracionEdilicia/ConfiguracionEdiliciaController.php"
    type:     annotation
    prefix:   /configuracion_edilicia
    
ri_test_ws:
    resource: "@RIWebServicesBundle/Controller/Test/TestController.php"
    type:     annotation
    prefix:   /test
    
ri_test_fosrest:
    resource: "@RIWebServicesBundle/Controller/Test/TestFosRestController.php"
    type: rest