ri_web_services:
    resource: "@RIWebServicesBundle/Controller/ConfiguracionEdiliciaController.php"
    type:     annotation
    prefix:   /ws
    
ri_test_ws:
    resource: "@RIWebServicesBundle/Controller/TestController.php"
    type:     annotation
    prefix:   /test
