ri_default:
    resource: "@RIWebServicesBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
    
ri_set:
    resource: "@RIWebServicesBundle/Controller/SET/SETController.php"
    type:     annotation
    prefix:   /set

ri_ws:
    resource: "@RIWebServicesBundle/Controller/WS/WSController.php"
    type: rest
    
ri_configuracion_edilicia:
    resource: "@RIWebServicesBundle/Controller/ConfiguracionEdilicia/ConfiguracionEdiliciaController.php"
    type:     annotation
    prefix:   /configuracion_edilicia

ri_test:
    resource: "@RIWebServicesBundle/Controller/Test/TestController.php"
    type:     annotation
    prefix:   /test
    
ri_test_ws:
    resource: "@RIWebServicesBundle/Controller/Test/TestWSController.php"
    type:     annotation
    prefix:   /test/ws
    
ri_logger:
    resource: "@RIWebServicesBundle/Controller/Logger/LoggerController.php"
    type:     annotation
    prefix:   /logger
