ws:
    resource: "@WSBundle/Resources/config/routing.yml"
    prefix:   /

servicios:
    resource: "@ServiciosBundle/Resources/config/routing.yml"
    prefix:   /

seguridad:
    resource: "@SeguridadBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path: /logout
    
assets:
    resource: "@AssetsBundle/Resources/config/routing.yml"
    prefix:   /assets

