db_hmi2_guaycuru_camas:
    resource: "@DBHmi2GuaycuruCamasBundle/Resources/config/routing.yml"
    prefix:   /

ws:
    resource: "@WSBundle/Resources/config/routing.yml"
    prefix:   /

servicios:
    resource: "@ServiciosBundle/Resources/config/routing.yml"
    prefix:   /

seguridad:
    resource: "@SeguridadBundle/Resources/config/routing.yml"
    prefix:   /
    
assets:
    resource: "@AssetsBundle/Resources/config/routing.yml"
    prefix:   /assets

