qiluazus:
    resource: "@QiluazusBundle/Controller/"
    type:     annotation
    prefix:   /guaycuru/qiluazus/

yaaukaniga:
    resource: "@YaaukanigaBundle/Controller/"
    type:     annotation
    prefix:   /guaycuru/yaaukaniga/

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
