services:
    
    configuracion_edilicia:
        class: Pruebas\WSBundle\Utils\ConfiguracionEdilicia
        arguments: ['@doctrine','@validator']

    informe_sincronizacion:
        class: Pruebas\WSBundle\Utils\InformeSincronizacion
        arguments: ['@doctrine']
        
    internaciones_pases:
        class: Pruebas\WSBundle\Utils\InternacionesPases
        arguments: ['@doctrine']