qiluazus_homepage:
    path:     /
    defaults:
        _controller: QiluazusBundle:Default:index
    
qiluazus_internaciones:
    pattern:     /internaciones
    defaults:
        _controller: QiluazusBundle:Listados:internaciones
    
qiluazus_ejemplo:
    pattern:     /ejemplo
    defaults:
        _controller: QiluazusBundle:Listados:ejemplo 
    
qiluazus_camas:
    pattern:     /camas/{id_efector}/{estado}/{idClasificacionCama}
    defaults:  
        _controller: QiluazusBundle:Listados:camas
        id_efector: 72
        estado: 'L'
        idClasificacionCama: 2
