db_hmi2:
    resource: "@DBHmi2Bundle/Controller/"
    type:     annotation
    prefix:   /

tembures:
    resource: "@TemburesBundle/Resources/config/routing.yml"
    prefix:   guaycuru/tembures

qiluazus:
    resource: "@QiluazusBundle/Resources/config/routing.yml"
    prefix:   guaycuru/qiluazus

yaaukaniga:
    resource: "@YaaukanigaBundle/Resources/config/routing.yml"
    prefix:   guaycuru/yaaukaniga

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
theme_aplicativo:
    resource: "@ThemeAplicativoBundle/Resources/config/routing.yml"
    prefix:   /